# Change these first
owner: sukanta21 # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: jobs.abroadworks.com
    url: https://jobs.abroadworks.com
    icon: https://jobsaas.co.in/_next/static/media/logo-centered.7244b026.svg
  - name: jobsaas.co.in
    url: https://jobsaas.co.in
    icon: https://jobsaas.co.in/_next/static/media/logo-centered.7244b026.svg
  # - name: Google
  #   url: https://www.google.com
  # - name: Wikipedia
  #   url: https://en.wikipedia.org
  # - name: Hacker News
  #   url: https://news.ycombinator.com
  # - name: Test Broken Site
  #   url: https://thissitedoesnotexist.koj.co

assignees: # Users to assign downtime issues (optional)
  - SukantaDas

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /up
  logoUrl: https://jobs.abroadworks.com/static/LogoSite.svg
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Monitor Jobsaas
  introTitle: "**UP** monitors Jobsass Websites!"
  introMessage: The monitoring **real-time** data from our [GitHub repository](https://sukanta21.github.io/up).
  favicon: https://jobsaas.co.in/_next/static/media/logo-centered.7244b026.svg
  theme: night 
  # Available themes are light, dark, night or ocean.
  navbar:
    - title: Status
      href: https://sukanta21.github.io/up
    - title: GitHub
      href: https://sukanta21.github.io/up
      # href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
footer: This page is hosted on [GitHub](https://sukanta21.github.io/up) project since @2023-10-27, & created by [Abroadworks](https://jobs.abroadworks.com).
    # footer: This page is hosted on GitHub [sukanta21/up]($REPO) project since @2023-10-27, & created by [Abroadworks](https://jobs.abroadworks.com).
  
workflowSchedule:
  graphs: "0 */6 * * *"
  responseTime: "10 */6 * * *"
  staticSite: "20 */6 * * *"
  summary: "30 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "40 */6 * * *"
  uptime: "*/5 * * * *"
